use std::fmt;
use std::fs;
use std::os::unix::fs::FileTypeExt;
use std::path::{Path, PathBuf};

use crate::config::{RelativeHomePath, RelativeHomePathError};
use crate::error::{NythError, StatusError};
use crate::sys::paths::NythPaths;

/// A path that changed during a session: it exists in `upper` because overlayfs copied it up on write, or created it fresh
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpperEntry {
    pub relative_path: PathBuf,
}

/// One outstanding difference between `upper` and what Home Manager knows about that path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PendingChange {
    /// Watched by Home Manager, and backed by a real source file in the dotfiles repo
    /// (`home.file.<name>.source` pointing at a path the user wrote not rendered one)
    RepoBacked { relative_path: PathBuf },
    /// Watched by Home Manager, but rendered by a `programs.*` module from Nix options
    /// (`home.file.<name>.text` was set)
    Generated { relative_path: PathBuf },
    /// Changed at a path nobody watches: something new, not managed by Home Manager at all
    Untracked { relative_path: PathBuf },
}

/// The dotfiles source of truth: `root` is a repo that mirrors $HOME 1:1 for the repo-backed subset
pub struct DotfilesRepo {
    pub root: PathBuf,
    pub repo_backed_paths: Vec<RelativeHomePath>,
    pub generated_paths: Vec<RelativeHomePath>,
}

impl DotfilesRepo {
    pub fn new(
        root: PathBuf,
        repo_backed_paths: Vec<RelativeHomePath>,
        generated_paths: Vec<RelativeHomePath>,
    ) -> Self {
        Self {
            root,
            repo_backed_paths,
            generated_paths,
        }
    }

    /// Pure lookup: which of the three states does `entry`'s path fall into
    pub fn compare(&self, entry: &UpperEntry) -> PendingChange {
        if matches_watched_path(&self.repo_backed_paths, &entry.relative_path) {
            PendingChange::RepoBacked {
                relative_path: entry.relative_path.clone(),
            }
        } else if matches_watched_path(&self.generated_paths, &entry.relative_path) {
            PendingChange::Generated {
                relative_path: entry.relative_path.clone(),
            }
        } else {
            PendingChange::Untracked {
                relative_path: entry.relative_path.clone(),
            }
        }
    }
}

/// `path` matches a watched-path if it's literally that path, or nested under it
fn matches_watched_path(watched_paths: &[RelativeHomePath], path: &Path) -> bool {
    watched_paths
        .iter()
        .any(|watched| path == watched.as_path() || path.starts_with(watched.as_path()))
}

/// argv-parsed inputs to `nyth status`/`nyth commit`, everything the wrapper generated by the Home Manager module passes in
#[derive(Debug, Clone, Default)]
pub struct RepoArgs {
    pub for_user: String,
    pub repo_root: Option<PathBuf>,
    pub repo_backed_paths: Vec<RelativeHomePath>,
    pub generated_paths: Vec<RelativeHomePath>,
}

impl RepoArgs {
    pub fn into_repo(self) -> DotfilesRepo {
        DotfilesRepo::new(
            self.repo_root.unwrap_or_else(|| PathBuf::from(".")),
            self.repo_backed_paths,
            self.generated_paths,
        )
    }

    pub fn paths(&self) -> NythPaths {
        NythPaths::for_user(&self.for_user)
    }
}

#[derive(Debug)]
pub enum RepoArgsError {
    MissingFlagValue {
        flag: &'static str,
    },
    MissingForUser,
    InvalidWatchedPath {
        flag: &'static str,
        raw: String,
        source: RelativeHomePathError,
    },
    UnexpectedArgument {
        raw: String,
    },
}

impl fmt::Display for RepoArgsError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingFlagValue { flag } => write!(f, "{flag} requires a value"),
            Self::MissingForUser => write!(f, "--for-user <name> is required"),
            Self::InvalidWatchedPath { flag, raw, source } => {
                write!(f, "invalid {flag} '{raw}': {source}")
            }
            Self::UnexpectedArgument { raw } => write!(
                f,
                "unexpected argument '{raw}', expected --for-user, --repo-root, --repo-backed, or --generated"
            ),
        }
    }
}

impl std::error::Error for RepoArgsError {}

/// Parses `nyth status|commit --for-user <name> [--repo-root <path>] [--repo-backed <rel>]... [--generated <rel>]...`
pub fn parse_repo_args(args: &[String]) -> Result<RepoArgs, RepoArgsError> {
    let mut for_user = None;
    let mut parsed = RepoArgs::default();
    let mut remaining = args.iter();

    while let Some(arg) = remaining.next() {
        match arg.as_str() {
            "--for-user" => {
                let raw = remaining
                    .next()
                    .ok_or(RepoArgsError::MissingFlagValue { flag: "--for-user" })?;
                for_user = Some(raw.clone());
            }
            "--repo-root" => {
                let raw = remaining.next().ok_or(RepoArgsError::MissingFlagValue {
                    flag: "--repo-root",
                })?;
                parsed.repo_root = Some(PathBuf::from(raw));
            }
            "--repo-backed" => {
                parsed
                    .repo_backed_paths
                    .push(parse_watched_path("--repo-backed", &mut remaining)?);
            }
            "--generated" => {
                parsed
                    .generated_paths
                    .push(parse_watched_path("--generated", &mut remaining)?);
            }
            other => {
                return Err(RepoArgsError::UnexpectedArgument {
                    raw: other.to_string(),
                });
            }
        }
    }

    parsed.for_user = for_user.ok_or(RepoArgsError::MissingForUser)?;
    Ok(parsed)
}

fn parse_watched_path(
    flag: &'static str,
    remaining: &mut std::slice::Iter<'_, String>,
) -> Result<RelativeHomePath, RepoArgsError> {
    let raw = remaining
        .next()
        .ok_or(RepoArgsError::MissingFlagValue { flag })?;
    RelativeHomePath::new(raw.as_str()).map_err(|source| RepoArgsError::InvalidWatchedPath {
        flag,
        raw: raw.clone(),
        source,
    })
}

/// Builds identity-scoped paths from `--for-user`, then reports pending changes against `repo`
pub fn status(args: &RepoArgs) -> Result<Vec<PendingChange>, NythError> {
    let paths = args.paths();
    let repo = args.clone().into_repo();
    nyth_status(&paths, &repo).map_err(NythError::Status)
}

/// Given what's already in `upper` and what the repo knows about, which changes are pending
pub fn diff_upper_against_repo(
    upper_entries: &[UpperEntry],
    repo: &DotfilesRepo,
) -> Vec<PendingChange> {
    upper_entries
        .iter()
        .map(|entry| repo.compare(entry))
        .collect()
}

/// Effect: The only I/O in the whole `status` path. Walks `upper` once, hands the result to the pure decision above
pub fn nyth_status(
    paths: &NythPaths,
    repo: &DotfilesRepo,
) -> Result<Vec<PendingChange>, StatusError> {
    let upper_entries = scan_upper_dir(&paths.upper)?;
    Ok(diff_upper_against_repo(&upper_entries, repo))
}

fn scan_upper_dir(upper_dir: &Path) -> Result<Vec<UpperEntry>, StatusError> {
    let mut entries = Vec::new();
    walk(upper_dir, upper_dir, &mut entries)?;
    Ok(entries)
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<UpperEntry>) -> Result<(), StatusError> {
    let read_dir = fs::read_dir(dir).map_err(|e| StatusError::ScanFailed {
        path: dir.to_path_buf(),
        message: e.to_string(),
    })?;

    for entry in read_dir {
        let entry = entry.map_err(|e| StatusError::ScanFailed {
            path: dir.to_path_buf(),
            message: e.to_string(),
        })?;
        let file_type = entry.file_type().map_err(|e| StatusError::ScanFailed {
            path: entry.path(),
            message: e.to_string(),
        })?;

        if file_type.is_char_device() {
            continue;
        }

        if file_type.is_dir() {
            walk(root, &entry.path(), out)?;
            continue;
        }

        let relative_path = entry
            .path()
            .strip_prefix(root)
            .expect("entry is always under root, we just walked it from there")
            .to_path_buf();
        out.push(UpperEntry { relative_path });
    }

    Ok(())
}
