use std::fs;
use std::io;
use std::os::unix::fs::FileTypeExt;
use std::path::{Path, PathBuf};

use eros::{Context, bail};

use crate::config::RelativeHomePath;
use crate::sys::paths::NythPaths;

/// A path that changed during a session: it exists in `upper` because overlayfs copied it up on write, or created it fresh
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpperEntry {
    pub relative_path: PathBuf,
}

/// One outstanding difference between `upper` and what Home Manager knows about that path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PendingChange {
    /// Watched by Home Manager, and backed by a real source file in the dotfiles repo
    /// (`home.file.<name>.source` pointing at a path the user wrote not rendered one)
    RepoBacked { relative_path: PathBuf },
    /// Watched by Home Manager, but rendered by a `programs.*` module from Nix options
    /// (`home.file.<name>.text` was set)
    Generated { relative_path: PathBuf },
    /// Changed at a path nobody watches: something new, not managed by Home Manager at all
    Untracked { relative_path: PathBuf },
}

/// The dotfiles source of truth: `root` is a repo that mirrors $HOME 1:1 for the repo-backed subset
pub struct DotfilesRepo {
    pub root: PathBuf,
    pub repo_backed_paths: Vec<RelativeHomePath>,
    pub generated_paths: Vec<RelativeHomePath>,
}

impl DotfilesRepo {
    pub fn new(
        root: PathBuf,
        repo_backed_paths: Vec<RelativeHomePath>,
        generated_paths: Vec<RelativeHomePath>,
    ) -> Self {
        Self {
            root,
            repo_backed_paths,
            generated_paths,
        }
    }

    /// Pure lookup: which of the three states does `entry`'s path fall into
    pub fn compare(&self, entry: &UpperEntry) -> PendingChange {
        if matches_watched_path(&self.repo_backed_paths, &entry.relative_path) {
            PendingChange::RepoBacked {
                relative_path: entry.relative_path.clone(),
            }
        } else if matches_watched_path(&self.generated_paths, &entry.relative_path) {
            PendingChange::Generated {
                relative_path: entry.relative_path.clone(),
            }
        } else {
            PendingChange::Untracked {
                relative_path: entry.relative_path.clone(),
            }
        }
    }
}

/// `path` matches a watched-path if it's literally that path, or nested under it
fn matches_watched_path(watched_paths: &[RelativeHomePath], path: &Path) -> bool {
    watched_paths
        .iter()
        .any(|watched| path == watched.as_path() || path.starts_with(watched.as_path()))
}

/// argv-parsed inputs to `nyth status`/`nyth commit`, everything the wrapper generated by the Home Manager module passes in
#[derive(Debug, Clone, Default)]
pub struct RepoArgs {
    pub for_user: String,
    pub repo_root: Option<PathBuf>,
    pub repo_backed_paths: Vec<RelativeHomePath>,
    pub generated_paths: Vec<RelativeHomePath>,
}

impl RepoArgs {
    pub fn into_repo(self) -> DotfilesRepo {
        DotfilesRepo::new(
            self.repo_root.unwrap_or_else(|| PathBuf::from(".")),
            self.repo_backed_paths,
            self.generated_paths,
        )
    }

    pub fn paths(&self) -> NythPaths {
        NythPaths::for_user(&self.for_user)
    }
}

/// Parses `nyth status|commit --for-user <name> [--repo-root <path>] [--repo-backed <rel>]... [--generated <rel>]...`
pub fn parse_repo_args(args: &[String]) -> eros::Result<RepoArgs> {
    let mut for_user = None;
    let mut parsed = RepoArgs::default();
    let mut remaining = args.iter();

    while let Some(arg) = remaining.next() {
        match arg.as_str() {
            "--for-user" => {
                let Some(raw) = remaining.next() else {
                    bail!("--for-user requires a value");
                };
                for_user = Some(raw.clone());
            }
            "--repo-root" => {
                let Some(raw) = remaining.next() else {
                    bail!("--repo-root requires a value");
                };
                parsed.repo_root = Some(PathBuf::from(raw));
            }
            "--repo-backed" => {
                parsed
                    .repo_backed_paths
                    .push(parse_watched_path("--repo-backed", &mut remaining)?);
            }
            "--generated" => {
                parsed
                    .generated_paths
                    .push(parse_watched_path("--generated", &mut remaining)?);
            }
            other => bail!(
                "unexpected argument '{}', expected --for-user, --repo-root, --repo-backed, or --generated",
                other
            ),
        }
    }

    let Some(for_user) = for_user else {
        bail!("--for-user <name> is required");
    };
    parsed.for_user = for_user;
    Ok(parsed)
}

fn parse_watched_path(
    flag: &'static str,
    remaining: &mut std::slice::Iter<'_, String>,
) -> eros::Result<RelativeHomePath> {
    let Some(raw) = remaining.next() else {
        bail!("{} requires a value", flag);
    };

    // Folded into the message rather than attached as context: this is argv the user typed, and it reads back to them on one line
    RelativeHomePath::new(raw.as_str())
        .map_err(|e| eros::error!("invalid {} '{}': {}", flag, raw, e))
}

/// Builds identity-scoped paths from `--for-user`, then reports pending changes against `repo`
pub fn status(args: &RepoArgs) -> eros::Result<Vec<PendingChange>> {
    let paths = args.paths();
    let repo = args.clone().into_repo();
    Ok(nyth_status(&paths, &repo)?)
}

/// Given what's already in `upper` and what the repo knows about, which changes are pending
pub fn diff_upper_against_repo(
    upper_entries: &[UpperEntry],
    repo: &DotfilesRepo,
) -> Vec<PendingChange> {
    upper_entries
        .iter()
        .map(|entry| repo.compare(entry))
        .collect()
}

/// Effect: The only I/O in the whole `status` path. Walks `upper` once, hands the result to the pure decision above
pub fn nyth_status(
    paths: &NythPaths,
    repo: &DotfilesRepo,
) -> eros::Result<Vec<PendingChange>, (io::Error,)> {
    let upper_entries = scan_upper_dir(&paths.upper)?;
    Ok(diff_upper_against_repo(&upper_entries, repo))
}

fn scan_upper_dir(upper_dir: &Path) -> eros::Result<Vec<UpperEntry>, (io::Error,)> {
    let mut entries = Vec::new();
    walk(upper_dir, upper_dir, &mut entries)?;
    Ok(entries)
}

// No `#[context]`: this recurses, and the attribute would stack one context frame per level of directory depth
fn walk(root: &Path, dir: &Path, out: &mut Vec<UpperEntry>) -> eros::Result<(), (io::Error,)> {
    let read_dir = fs::read_dir(dir).with_user_context(|| format!("scanning {}", dir.display()))?;

    for entry in read_dir {
        let entry = entry.with_user_context(|| format!("scanning {}", dir.display()))?;
        let file_type = entry
            .file_type()
            .with_context(|| format!("reading the type of {}", entry.path().display()))?;

        if file_type.is_char_device() {
            continue;
        }

        if file_type.is_dir() {
            walk(root, &entry.path(), out)?;
            continue;
        }

        let relative_path = entry
            .path()
            .strip_prefix(root)
            .expect("entry is always under root, we just walked it from there")
            .to_path_buf();
        out.push(UpperEntry { relative_path });
    }

    Ok(())
}
